name: Terraform Plan
on: [pull_request]
jobs:
  apply:
    name: Terraform Plan
    runs-on: ubuntu-latest
    steps:
    - name: Filter to PR Opened
      uses: actions/bin/filter@master
      with:
        args: "action 'opened|synchronize|rerequested'"
    - uses: actions/checkout@v1
    - name: Terraform - Format
      uses: hashicorp/terraform-github-actions@v0.6.1
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"
        tf_actions_version: 0.12.21
        tf_actions_subcommand: fmt
        tf_actions_working_dir: '.'
        tf_actions_comment: "true"
    - name: Terraform - Init
      uses: hashicorp/terraform-github-actions@v0.6.1
      env:
        GOOGLE_CREDENTIALS: "${{ secrets.GOOGLE_CREDENTIALS }}"
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"
        tf_actions_version: 0.12.21
        tf_actions_subcommand: init
        tf_actions_working_dir: '.'
        tf_actions_comment: "true"
    - name: Terraform - Validate
      uses: hashicorp/terraform-github-actions@v0.6.1
      env:
        GOOGLE_CREDENTIALS: "${{ secrets.GOOGLE_CREDENTIALS }}"
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"
        tf_actions_version: 0.12.21
        tf_actions_subcommand: validate
        tf_actions_working_dir: '.'
        tf_actions_comment: "true"
    - name: Terraform - Plan
      uses: hashicorp/terraform-github-actions@v0.6.1
      env:
        GOOGLE_CREDENTIALS: "${{ secrets.GOOGLE_CREDENTIALS }}"
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"
        tf_actions_version: 0.12.21
        tf_actions_subcommand: plan
        tf_actions_working_dir: '.'
        tf_actions_comment: "true"
